// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Parking_Lot_Reservation.Data;

namespace Parking_Lot_Reservation.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20211023142945_Add_charger")]
    partial class Add_charger
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("Parking_Lot_Reservation.Models.ParkingSpaceModel", b =>
                {
                    b.Property<int>("ParkingSpaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCharger")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsReserved")
                        .HasColumnType("INTEGER");

                    b.HasKey("ParkingSpaceId");

                    b.ToTable("ParkingSpaces");
                });

            modelBuilder.Entity("Parking_Lot_Reservation.Models.PersonModel", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParkingSpaceModel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Surname")
                        .HasColumnType("TEXT");

                    b.HasKey("PersonId");

                    b.HasIndex("ParkingSpaceModel");

                    b.ToTable("People");
                });

            modelBuilder.Entity("Parking_Lot_Reservation.Models.PersonModel", b =>
                {
                    b.HasOne("Parking_Lot_Reservation.Models.ParkingSpaceModel", "ParkingSpaceId")
                        .WithMany()
                        .HasForeignKey("ParkingSpaceModel");

                    b.Navigation("ParkingSpaceId");
                });
#pragma warning restore 612, 618
        }
    }
}
