// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Parking_Lot_Reservation.Data;

namespace Parking_Lot_Reservation.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("Parking_Lot_Reservation.Models.ParkingSpaceModel", b =>
                {
                    b.Property<int>("ParkingSpaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasCharger")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsReserved")
                        .HasColumnType("INTEGER");

                    b.HasKey("ParkingSpaceId");

                    b.ToTable("ParkingSpaces");
                });

            modelBuilder.Entity("Parking_Lot_Reservation.Models.PersonModel", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParkingSpaceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Surname")
                        .HasColumnType("TEXT");

                    b.HasKey("PersonId");

                    b.HasIndex("ParkingSpaceId");

                    b.ToTable("People");
                });

            modelBuilder.Entity("Parking_Lot_Reservation.Models.PersonModel", b =>
                {
                    b.HasOne("Parking_Lot_Reservation.Models.ParkingSpaceModel", "ParkingSpace")
                        .WithMany()
                        .HasForeignKey("ParkingSpaceId");

                    b.Navigation("ParkingSpace");
                });
#pragma warning restore 612, 618
        }
    }
}
